apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-boilerplate.fullname" . }}-secrets
type: Opaque
data:
  APP_KEY: {{ .Values.appKey | default "base64-encoded-key" | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc | quote }}
